# Generated by Django 5.2.16 on 2026-07-25 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TEXT_CHAT', 'Text Chat'), ('VOICE_CHAT', 'Voice Chat'), ('OCR', 'OCR'), ('FEEDBACK', 'Feedback')], max_length=30)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='analytics_e_user_id_f87fa1_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx')],
            },
        ),
    ]
