openapi: 3.0.3
info:
  title: Farmer Voice AI API
  version: 1.0.0
  description: Backend APIs
paths:
  /api/accounts/change-password/:
    post:
      operationId: accounts_change_password_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/accounts/login/:
    post:
      operationId: accounts_login_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /api/accounts/logout/:
    post:
      operationId: accounts_logout_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logout'
          description: ''
  /api/accounts/profile/:
    get:
      operationId: accounts_profile_retrieve
      tags:
      - accounts
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
  /api/accounts/register/:
    post:
      operationId: accounts_register_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/accounts/token/refresh/:
    post:
      operationId: accounts_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/knowledge/:
    get:
      operationId: knowledge_list
      description: List all active knowledge records.
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Knowledge'
          description: ''
  /api/knowledge/sources/:
    get:
      operationId: knowledge_sources_list
      description: List all uploaded knowledge sources.
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KnowledgeSource'
          description: ''
  /api/knowledge/upload/:
    post:
      operationId: knowledge_upload_create
      description: Upload Knowledge Source
      tags:
      - Knowledge
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/KnowledgeUploadRequest'
            encoding:
              file:
                contentType: multipart/form-data
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KnowledgeUploadRequest'
            encoding:
              file:
                contentType: multipart/form-data
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeSource'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    CategoryEnum:
      enum:
      - Disease
      - Pest
      - Fertilizer
      - Seed
      - Soil
      - Weather
      - Market
      - Scheme
      - Irrigation
      - Harvest
      - Storage
      - General
      type: string
      description: |-
        * `Disease` - Disease
        * `Pest` - Pest
        * `Fertilizer` - Fertilizer
        * `Seed` - Seed
        * `Soil` - Soil
        * `Weather` - Weather
        * `Market` - Market
        * `Scheme` - Government Scheme
        * `Irrigation` - Irrigation
        * `Harvest` - Harvest
        * `Storage` - Storage
        * `General` - General
    ChangePasswordRequest:
      type: object
      properties:
        old_password:
          type: string
          writeOnly: true
          minLength: 1
        new_password:
          type: string
          writeOnly: true
          minLength: 1
        confirm_password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - confirm_password
      - new_password
      - old_password
    Knowledge:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        crop:
          type: string
          maxLength: 100
        category:
          $ref: '#/components/schemas/CategoryEnum'
        subcategory:
          type: string
          maxLength: 100
        stage:
          type: string
          maxLength: 100
        question:
          type: string
        answer:
          type: string
        keywords:
          type: string
        language:
          type: string
          maxLength: 20
        priority:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        knowledge_source:
          type: integer
      required:
      - answer
      - created_at
      - crop
      - id
      - knowledge_source
      - question
      - updated_at
    KnowledgeSource:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        source_type:
          $ref: '#/components/schemas/KnowledgeSourceSourceTypeEnum'
        source_name:
          type: string
          maxLength: 255
        file:
          type: string
          format: uri
          nullable: true
        language:
          type: string
          maxLength: 20
        version:
          type: string
          maxLength: 20
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - source_type
      - title
      - updated_at
    KnowledgeSourceSourceTypeEnum:
      enum:
      - excel
      - csv
      - pdf
      - docx
      - website
      - api
      - image
      type: string
      description: |-
        * `excel` - Excel
        * `csv` - CSV
        * `pdf` - PDF
        * `docx` - DOCX
        * `website` - Website
        * `api` - API
        * `image` - Image
    KnowledgeUploadRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
        source_type:
          $ref: '#/components/schemas/KnowledgeUploadSourceTypeEnum'
        language:
          type: string
          minLength: 1
          default: en
      required:
      - file
      - source_type
      - title
    KnowledgeUploadSourceTypeEnum:
      enum:
      - excel
      - csv
      type: string
      description: |-
        * `excel` - excel
        * `csv` - csv
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
      - email
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    Logout:
      type: object
      properties:
        refresh:
          type: string
      required:
      - refresh
    LogoutRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
    Profile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          readOnly: true
        first_name:
          type: string
          readOnly: true
        last_name:
          type: string
          readOnly: true
        phone_number:
          type: string
          readOnly: true
        role:
          allOf:
          - $ref: '#/components/schemas/RoleEnum'
          readOnly: true
        date_joined:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_joined
      - email
      - first_name
      - id
      - last_name
      - phone_number
      - role
    Register:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 254
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        phone_number:
          type: string
          maxLength: 15
        role:
          $ref: '#/components/schemas/RoleEnum'
      required:
      - email
      - first_name
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 1
          maxLength: 254
        first_name:
          type: string
          minLength: 1
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        phone_number:
          type: string
          maxLength: 15
        role:
          $ref: '#/components/schemas/RoleEnum'
        password:
          type: string
          writeOnly: true
          minLength: 8
          maxLength: 128
        confirm_password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - confirm_password
      - email
      - first_name
      - password
    RoleEnum:
      enum:
      - ADMIN
      - FARMER
      - EXPERT
      type: string
      description: |-
        * `ADMIN` - Admin
        * `FARMER` - Farmer
        * `EXPERT` - Expert
    StatusEnum:
      enum:
      - pending
      - processing
      - completed
      - failed
      type: string
      description: |-
        * `pending` - Pending
        * `processing` - Processing
        * `completed` - Completed
        * `failed` - Failed
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
