# Generated by Django 5.2.16 on 2026-07-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('website', 'Website'), ('api', 'API'), ('image', 'Image')], max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_sources/')),
                ('language', models.CharField(default='en', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Disease', 'Disease'), ('Pest', 'Pest'), ('Fertilizer', 'Fertilizer'), ('Seed', 'Seed'), ('Soil', 'Soil'), ('Weather', 'Weather'), ('Market', 'Market'), ('Scheme', 'Government Scheme'), ('Irrigation', 'Irrigation'), ('Harvest', 'Harvest'), ('Storage', 'Storage'), ('General', 'General')], default='General', max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='knowledge_base.knowledgesource')),
            ],
        ),
    ]
