# Generated by Django 5.2.16 on 2026-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='failed_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='processed_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='total_records',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
