# Generated by Django 5.2.16 on 2026-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgesource_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='domain',
            field=models.CharField(blank=True, help_text='Disease, Pest, Fertilizer, Irrigation, Weather, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='normalized_question',
            field=models.TextField(blank=True, help_text='Normalized question used for multilingual search.'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='search_text',
            field=models.TextField(blank=True, help_text='Combined searchable text used for embeddings and semantic search.'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='crop',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
