"""
Custom exceptions for Farmer Voice AI.

Purpose:
- Centralize application-specific exceptions
- Avoid scattered generic Exception usage
- Make API error handling predictable
- Separate expected application failures from programming errors

These exceptions should contain technical information for the
backend. Farmer-facing messages should normally be generated by
the response layer rather than exposing internal exception text.
"""

# ============================================================
# BASE EXCEPTION
# ============================================================


class FarmerVoiceAIException(Exception):
    """
    Base exception for expected Farmer Voice AI application errors.

    All custom application exceptions should inherit from this
    class so they can be caught centrally when required.
    """

    default_message = "An application error occurred."
    error_code = "application_error"

    def __init__(
        self,
        message=None,
        *,
        details=None,
    ):
        self.message = message or self.default_message
        self.details = details

        super().__init__(self.message)

    def to_dict(self):
        data = {
            "error": self.error_code,
            "message": self.message,
        }

        if self.details is not None:
            data["details"] = self.details

        return data


# ============================================================
# VALIDATION EXCEPTIONS
# ============================================================


class ValidationError(FarmerVoiceAIException):
    """
    Raised when application-level validation fails.
    """

    default_message = "Validation failed."
    error_code = "validation_error"


class InvalidRequestError(ValidationError):
    """
    Raised when incoming request data is malformed or incomplete.
    """

    default_message = "Invalid request."
    error_code = "invalid_request"


class MissingRequiredFieldError(ValidationError):
    """
    Raised when a required field is missing.
    """

    default_message = "A required field is missing."
    error_code = "missing_required_field"


class UnsupportedLanguageError(ValidationError):
    """
    Raised when the requested language cannot be processed.
    """

    default_message = "Unsupported language."
    error_code = "unsupported_language"


class InvalidUnitError(ValidationError):
    """
    Raised when an agricultural measurement/unit cannot be
    safely normalized.
    """

    default_message = "Invalid or unsupported unit."
    error_code = "invalid_unit"


# ============================================================
# KNOWLEDGE BASE EXCEPTIONS
# ============================================================


class KnowledgeBaseError(FarmerVoiceAIException):
    """
    Base exception for knowledge-base operations.
    """

    default_message = "Knowledge base operation failed."
    error_code = "knowledge_base_error"


class KnowledgeNotFoundError(KnowledgeBaseError):
    """
    Raised when trusted knowledge cannot be found.
    """

    default_message = "No matching knowledge was found."
    error_code = "knowledge_not_found"


class KnowledgeImportError(KnowledgeBaseError):
    """
    Raised when importing a knowledge source fails.
    """

    default_message = "Knowledge import failed."
    error_code = "knowledge_import_error"


class KnowledgeValidationError(KnowledgeBaseError):
    """
    Raised when an imported knowledge record fails validation.
    """

    default_message = "Knowledge record validation failed."
    error_code = "knowledge_validation_error"


class KnowledgeQualityError(KnowledgeBaseError):
    """
    Raised when knowledge does not meet minimum quality
    requirements.
    """

    default_message = "Knowledge quality requirements were not met."
    error_code = "knowledge_quality_error"


class UnsupportedKnowledgeSourceError(KnowledgeBaseError):
    """
    Raised when attempting to import an unsupported source type.
    """

    default_message = "Unsupported knowledge source type."
    error_code = "unsupported_knowledge_source"


class KnowledgeSourceProcessingError(KnowledgeBaseError):
    """
    Raised when a supported knowledge source cannot be processed.
    """

    default_message = "Knowledge source processing failed."
    error_code = "knowledge_source_processing_error"


# ============================================================
# QUERY / ANALYSIS EXCEPTIONS
# ============================================================


class QueryAnalysisError(FarmerVoiceAIException):
    """
    Raised when user query analysis fails.
    """

    default_message = "Unable to analyze the query."
    error_code = "query_analysis_error"


class ConceptExtractionError(QueryAnalysisError):
    """
    Raised when concepts cannot be extracted safely.
    """

    default_message = "Concept extraction failed."
    error_code = "concept_extraction_error"


class CropResolutionError(QueryAnalysisError):
    """
    Raised when crop resolution itself fails technically.

    IMPORTANT:
    An unknown crop is not necessarily an error.

    Universal crop support means a crop may legitimately not
    exist in the current knowledge database.

    This exception should therefore be used for resolver failures,
    not simply because a crop was not recognized.
    """

    default_message = "Crop resolution failed."
    error_code = "crop_resolution_error"


class TopicClassificationError(QueryAnalysisError):
    """
    Raised when agricultural topic classification fails.
    """

    default_message = "Topic classification failed."
    error_code = "topic_classification_error"


# ============================================================
# RETRIEVAL EXCEPTIONS
# ============================================================


class RetrievalError(FarmerVoiceAIException):
    """
    Base exception for retrieval failures.
    """

    default_message = "Knowledge retrieval failed."
    error_code = "retrieval_error"


class SearchError(RetrievalError):
    """
    Raised when search execution fails.
    """

    default_message = "Knowledge search failed."
    error_code = "search_error"


class BM25SearchError(RetrievalError):
    """
    Raised when BM25 retrieval fails.
    """

    default_message = "BM25 search failed."
    error_code = "bm25_search_error"


class SemanticSearchError(RetrievalError):
    """
    Raised when semantic retrieval fails.
    """

    default_message = "Semantic search failed."
    error_code = "semantic_search_error"


class FuzzySearchError(RetrievalError):
    """
    Raised when fuzzy retrieval fails.
    """

    default_message = "Fuzzy search failed."
    error_code = "fuzzy_search_error"


class EmbeddingError(RetrievalError):
    """
    Raised when embedding generation fails.
    """

    default_message = "Embedding generation failed."
    error_code = "embedding_error"


class VectorStoreError(RetrievalError):
    """
    Raised when vector-store operations fail.
    """

    default_message = "Vector store operation failed."
    error_code = "vector_store_error"


class RankingError(RetrievalError):
    """
    Raised when hybrid ranking fails.
    """

    default_message = "Retrieval ranking failed."
    error_code = "ranking_error"


# ============================================================
# RELEVANCE / GROUNDING EXCEPTIONS
# ============================================================


class RelevanceError(FarmerVoiceAIException):
    """
    Base exception for relevance processing.
    """

    default_message = "Relevance evaluation failed."
    error_code = "relevance_error"


class IrrelevantKnowledgeError(RelevanceError):
    """
    Optional exception for flows where irrelevant retrieval
    should stop processing through exception handling.

    Current ChatService may instead return a normal controlled
    irrelevant response, which is also valid.
    """

    default_message = "Retrieved knowledge is not relevant."
    error_code = "irrelevant_knowledge"


class CropMismatchError(RelevanceError):
    """
    Represents a mismatch between an explicitly identified crop
    in the user query and retrieved crop-specific evidence.

    Example:
        Query crop     -> Wheat
        Evidence crop  -> Soybean

    This protects against cross-crop hallucination.
    """

    default_message = "Retrieved knowledge belongs to a different crop."
    error_code = "crop_mismatch"


class InsufficientEvidenceError(RelevanceError):
    """
    Raised when retrieval does not provide sufficient independent
    evidence for answer generation.
    """

    default_message = "Insufficient evidence for a reliable answer."
    error_code = "insufficient_evidence"


# ============================================================
# LLM / GENERATION EXCEPTIONS
# ============================================================


class LLMError(FarmerVoiceAIException):
    """
    Base exception for local LLM operations.
    """

    default_message = "Language model operation failed."
    error_code = "llm_error"


class LLMUnavailableError(LLMError):
    """
    Raised when the configured model/service is unavailable.
    """

    default_message = "Language model is unavailable."
    error_code = "llm_unavailable"


class LLMGenerationError(LLMError):
    """
    Raised when answer generation fails.
    """

    default_message = "Answer generation failed."
    error_code = "llm_generation_error"


class EmptyGenerationError(LLMGenerationError):
    """
    Raised when the model returns no usable text.
    """

    default_message = "Language model returned an empty response."
    error_code = "empty_generation"


# ============================================================
# ANSWER SAFETY EXCEPTIONS
# ============================================================


class AnswerValidationError(FarmerVoiceAIException):
    """
    Base exception for generated-answer validation.
    """

    default_message = "Generated answer failed validation."
    error_code = "answer_validation_error"


class UnsupportedEntityError(AnswerValidationError):
    """
    Raised when an agricultural entity in the answer is not
    supported by retrieved evidence.
    """

    default_message = "Answer contains an unsupported agricultural entity."
    error_code = "unsupported_entity"


class UnsupportedNumericInformationError(AnswerValidationError):
    """
    Raised when generated numeric advice is absent from evidence.
    """

    default_message = "Answer contains unsupported numeric information."
    error_code = "unsupported_numeric_information"


class UnsupportedProductError(AnswerValidationError):
    """
    Raised when a generated chemical/product name cannot be
    grounded in trusted evidence.
    """

    default_message = "Answer contains an unsupported agricultural product."
    error_code = "unsupported_product"


class RepeatedGenerationError(AnswerValidationError):
    """
    Raised when generated text contains abnormal repetition.
    """

    default_message = "Repeated answer generation detected."
    error_code = "repeated_generation"


class MalformedGenerationError(AnswerValidationError):
    """
    Raised when generated output contains malformed/corrupted text.
    """

    default_message = "Generated answer is malformed."
    error_code = "malformed_generation"


# ============================================================
# CONVERSATION / MEMORY EXCEPTIONS
# ============================================================


class ConversationError(FarmerVoiceAIException):
    """
    Base exception for conversation operations.
    """

    default_message = "Conversation operation failed."
    error_code = "conversation_error"


class ConversationNotFoundError(ConversationError):
    """
    Raised when a requested conversation does not exist.
    """

    default_message = "Conversation was not found."
    error_code = "conversation_not_found"


class MemoryError(ConversationError):
    """
    Raised when conversation-memory processing fails.

    Note:
    This intentionally refers to chatbot memory, not Python's
    built-in memory-allocation errors.
    """

    default_message = "Conversation memory processing failed."
    error_code = "conversation_memory_error"


class ContextBuildError(ConversationError):
    """
    Raised when conversational context cannot be constructed.
    """

    default_message = "Conversation context could not be built."
    error_code = "context_build_error"


# ============================================================
# SPEECH EXCEPTIONS
# ============================================================


class SpeechError(FarmerVoiceAIException):
    """
    Base exception for speech services.
    """

    default_message = "Speech processing failed."
    error_code = "speech_error"


class SpeechToTextError(SpeechError):
    """
    Raised when voice transcription fails.
    """

    default_message = "Speech-to-text processing failed."
    error_code = "speech_to_text_error"


class TextToSpeechError(SpeechError):
    """
    Raised when speech generation fails.
    """

    default_message = "Text-to-speech processing failed."
    error_code = "text_to_speech_error"


class InvalidAudioError(SpeechError):
    """
    Raised when uploaded/recorded audio cannot be processed.
    """

    default_message = "Invalid audio input."
    error_code = "invalid_audio"


class UnsupportedAudioFormatError(SpeechError):
    """
    Raised when the supplied audio format is unsupported.
    """

    default_message = "Unsupported audio format."
    error_code = "unsupported_audio_format"


# ============================================================
# OCR EXCEPTIONS
# ============================================================


class OCRError(FarmerVoiceAIException):
    """
    Base exception for OCR/image text extraction.
    """

    default_message = "OCR processing failed."
    error_code = "ocr_error"


class InvalidImageError(OCRError):
    """
    Raised when an image cannot be processed.
    """

    default_message = "Invalid image input."
    error_code = "invalid_image"


class OCRExtractionError(OCRError):
    """
    Raised when text extraction from an image fails.
    """

    default_message = "Text could not be extracted from the image."
    error_code = "ocr_extraction_error"


# ============================================================
# EXTERNAL SOURCE EXCEPTIONS
# ============================================================


class ExternalSourceError(FarmerVoiceAIException):
    """
    Base exception for future trusted external agricultural
    knowledge integrations.
    """

    default_message = "External knowledge source failed."
    error_code = "external_source_error"


class ExternalAPIError(ExternalSourceError):
    """
    Raised when an external agricultural API fails.
    """

    default_message = "External agricultural API request failed."
    error_code = "external_api_error"


class ExternalSourceTimeoutError(ExternalSourceError):
    """
    Raised when an external source exceeds its allowed timeout.
    """

    default_message = "External knowledge source timed out."
    error_code = "external_source_timeout"


# ============================================================
# AUTHORIZATION EXCEPTIONS
# ============================================================


class AuthorizationError(FarmerVoiceAIException):
    """
    Base exception for authorization failures.
    """

    default_message = "You are not authorized to perform this action."
    error_code = "authorization_error"


class PermissionDeniedError(AuthorizationError):
    """
    Raised when a user lacks the required permission.
    """

    default_message = "Permission denied."
    error_code = "permission_denied"


# ============================================================
# CONFIGURATION EXCEPTIONS
# ============================================================


class ConfigurationError(FarmerVoiceAIException):
    """
    Raised when required application configuration is invalid.
    """

    default_message = "Application configuration is invalid."
    error_code = "configuration_error"


class ServiceConfigurationError(ConfigurationError):
    """
    Raised when an AI/search/speech service is incorrectly
    configured.
    """

    default_message = "Service configuration is invalid."
    error_code = "service_configuration_error"
